const SET_ADMIN = "ASSESMENT_FORM/SET_ADMIN";
const SET_ID = "ASSESMENT_FORM/SET_ID";
const SET_LOADING = "ASSESMENT_FORM/SET_LOADING";
const ADD_VIDEOBLOCK = "ASSESMENT_FORM/ADD_VIDEOBLOCK";
const REMOVE_VIDEOBLOCK = "ASSESMENT_FORM/REMOVE_VIDEOBLOCK";
const SET_BASIC_VIDEOBLOCK = "ASSESMENT_FORM/SET_BASIC_VIDEOBLOCK";
const CHANGE_VIDEOBLOCK = "ASSESMENT_FORM/CHANGE_VIDEOBLOCK";
const CLEAR_VIDEOBLOCKS = "ASSESMENT_FORM/CLEAR_VIDEOBLOCKS";


export {
    SET_ADMIN,
    SET_ID,
    SET_LOADING,
    ADD_VIDEOBLOCK,
    REMOVE_VIDEOBLOCK,
    SET_BASIC_VIDEOBLOCK,
    CHANGE_VIDEOBLOCK,
    CLEAR_VIDEOBLOCKS
};
