const SET_ADMIN = "ASSESMENT_FORM/SET_ADMIN";
const SET_ID = "ASSESMENT_FORM/SET_ID";
const SET_LOADING = "ASSESMENT_FORM/SET_LOADING";
const ADD_VIDEOBLOCK = "ASSESMENT_FORM/ADD_VIDEOBLOCK";
const REMOVE_VIDEOBLOCK = "ASSESMENT_FORM/REMOVE_VIDEOBLOCK";
const SET_BASIC_VIDEOBLOCK = "ASSESMENT_FORM/SET_BASIC_VIDEOBLOCK";


export {
    SET_ADMIN,
    SET_ID,
    SET_LOADING,
    ADD_VIDEOBLOCK,
    REMOVE_VIDEOBLOCK,
    SET_BASIC_VIDEOBLOCK
};
