const SET_ERROR = "ASSESMENT_FORM/SET_ERROR";
const SET_RELOAD_ERROR_PAGE_REQUEST = "ASSESMENT_FORM/SET_RELOAD_ERROR_PAGE_REQUEST";
const SET_RELOAD_CONF_PAGE_REQUEST = "ASSESMENT_FORM/SET_RELOAD_CONF_PAGE_REQUEST";


export {
    SET_ERROR,
    SET_RELOAD_ERROR_PAGE_REQUEST,
    SET_RELOAD_CONF_PAGE_REQUEST
};
