const SET_PAGE_HOME = "ASSESMENT_FORM/SET_PAGE_HOME";
const SET_PAGE_CONF = "ASSESMENT_FORM/SET_PAGE_CONF";
const SET_PAGE_ERROR = "ASSESMENT_FORM/SET_PAGE_ERROR";


export {
    SET_PAGE_HOME,
    SET_PAGE_CONF,
    SET_PAGE_ERROR,
};
